name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
       with:
          submodules: true

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install plugins for theme Even
        run: |
        npm install hexo-renderer-scss hexo-renderer-swig --save
        npm uninstall hexo-renderer-sass
        npm i --save hexo-renderer-sass-next

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public